services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    environment:
      - SONARQUBE_URL=http://sonarqube:9000
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      - SONAR_TOKEN=sqa_e8b62edc51ebc76adb77ea42811b520042e46139
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - .:/network-kpi-dashboard
    networks:
      - jenkins-sonar-network
  
  sonarqube:
    image: sonarqube:9-community
    environment:
      - sonar.forceAuthentication=false
    ports:
      - "9000:9000"
    networks:
      - jenkins-sonar-network

networks:
  jenkins-sonar-network:
    driver: bridge