services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    environment:
      - SONARQUBE_URL=http://sonarqube:9000
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      - .:/network-kpi-dashboard
    networks:
      - jenkins-sonar-network
  
  sonarqube:
    image: sonarqube:9-community
    ports:
      - "9000:9000"
    networks:
      - jenkins-sonar-network
# admin token = sqa_e8b62edc51ebc76adb77ea42811b520042e46139

networks:
  jenkins-sonar-network:
    driver: bridge