services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    user: root
    privileged: true
    environment:
      - SONARQUBE_URL=http://sonarqube:9000
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      - SONAR_TOKEN=sqa_d66d508eac98afa638cdd7184108a01c328db674
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - .:/network-kpi-dashboard
      -  /var/run/docker.sock:/var/run/docker.sock:ro

  sonarqube:
    image: sonarqube:9-community
    environment:
      - sonar.forceAuthentication=false
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_conf:/opt/sonarqube/conf
